export const teachers = [
  {
    id: 1,
    name: "Tony Reichert",
    email: "tony.reichert@example.com",
    language: "English",
    notes: "CEO of the company",
    role: "Teacher",
  },
  {
    id: 2,
    name: "Zoey Lang",
    email: "zoey.lang@example.com",
    language: "French",
    notes: "Tech Lead in Development",
    avatar: "https://i.pravatar.cc/150?img=9",
    role: "Teacher",
  },
  {
    id: 3,
    name: "Jane Fisher",
    email: "jane.fisher@example.com",
    language: "German",
    notes: "Senior Developer",
    avatar: "https://i.pravatar.cc/150?img=10",
    role: "Teacher",
  },
  {
    id: 4,
    name: "William Howard",
    email: "william.howard@example.com",
    language: "Italian",
    notes: "Marketing Manager",
    avatar: "https://i.pravatar.cc/150?img=11",
    role: "Teacher",
  },
  {
    id: 5,
    name: "Kristen Copper",
    email: "kristen.cooper@example.com",
    language: "Spanish",
    notes: "Sales Manager",
    avatar: "https://i.pravatar.cc/150?img=12",
    role: "Teacher",
  },
  {
    id: 6,
    name: "Brian Kim",
    email: "brian.kim@example.com",
    language: "English",
    notes: "P. Manager in Management",
    avatar: "https://i.pravatar.cc/150?img=13",
    role: "Teacher",
  },
  {
    id: 7,
    name: "Michael Hunt",
    email: "michael.hunt@example.com",
    language: "French",
    notes: "Designer in Design",
    avatar: "https://i.pravatar.cc/150?img=14",
    role: "Teacher",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    email: "samantha.brooks@example.com",
    language: "German",
    notes: "HR Manager in HR",
    avatar: "https://i.pravatar.cc/150?img=15",
    role: "Teacher",
  },
  {
    id: 9,
    name: "Frank Harrison",
    email: "frank.harrison@example.com",
    language: "Italian",
    notes: "F. Manager in Finance",
    avatar: "https://i.pravatar.cc/150?img=16",
    role: "Teacher",
  },
  {
    id: 10,
    name: "Emma Adams",
    email: "emma.adams@example.com",
    language: "Spanish",
    notes: "Ops Manager in Operations",
    avatar: "https://i.pravatar.cc/150?img=17",
    role: "Teacher",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    email: "brandon.stevens@example.com",
    language: "English",
    notes: "Jr. Dev in Development",
    avatar: "https://i.pravatar.cc/150?img=18",
    role: "Teacher",
  },
  {
    id: 12,
    name: "Megan Richards",
    email: "megan.richards@example.com",
    language: "French",
    notes: "P. Manager in Product",
    avatar: "https://i.pravatar.cc/150?img=19",
    role: "Teacher",
  },
  {
    id: 13,
    name: "Oliver Scott",
    email: "oliver.scott@example.com",
    language: "German",
    notes: "S. Manager in Security",
    avatar: "https://i.pravatar.cc/150?img=20",
    role: "Teacher",
  },
  {
    id: 14,
    name: "Grace Allen",
    email: "grace.allen@example.com",
    language: "Italian",
    notes: "M. Specialist in Marketing",
    avatar: "https://i.pravatar.cc/150?img=21",
    role: "Teacher",
  },
  {
    id: 15,
    name: "Noah Carter",
    email: "noah.carter@example.com",
    language: "Spanish",
    notes: "IT Specialist in I. Technology",
    avatar: "https://i.pravatar.cc/150?img=22",
    role: "Teacher",
  },
  {
    id: 16,
    name: "Ava Perez",
    email: "ava.perez@example.com",
    language: "English",
    notes: "Manager in Sales",
    avatar: "https://i.pravatar.cc/150?img=23",
    role: "Teacher",
  },
  {
    id: 17,
    name: "Liam Johnson",
    email: "liam.johnson@example.com",
    language: "French",
    notes: "Data Analyst in Analysis",
    avatar: "https://i.pravatar.cc/150?img=24",
    role: "Teacher",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    email: "sophia.taylor@example.com",
    language: "German",
    notes: "QA Analyst in Testing",
    avatar: "https://i.pravatar.cc/150?img=25",
    role: "Teacher",
  },
  {
    id: 19,
    name: "Lucas Harris",
    email: "lucas.harris@example.com",
    language: "Italian",
    notes: "Administrator in Information Technology",
    avatar: "https://i.pravatar.cc/150?img=26",
    role: "Teacher",
  },
  {
    id: 20,
    name: "Mia Robinson",
    email: "mia.robinson@example.com",
    language: "Spanish",
    notes: "Coordinator in Operations",
    avatar: "https://i.pravatar.cc/150?img=27",
    role: "Teacher",
  },
];
